# Generated by Django 4.0.6 on 2023-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_date', models.DateField()),
                ('movname', models.CharField(max_length=30)),
                ('actorname', models.CharField(max_length=30)),
                ('actressname', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
